# Generated by Django 2.1 on 2019-03-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190308_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='activate',
            new_name='active',
        ),
    ]
