# Generated by Django 2.1 on 2019-04-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190321_0435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created']},
        ),
    ]
